spring:
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
    show-sql: false
    open-in-view: false
  profiles:
    active: dev
  jackson:
    deserialization:
      READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE: true

server:
  servlet:
    context-path: /api/v1

