spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_rest?characterEncoding=UTF-8&serverTimezone=GMT%2b8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&useSSL=false&connectTimeout=30000000
    username: sr
    password: sr123
    sqlScriptEncoding: UTF-8
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
  mvc:
    log-request-details: false
  devtools:
    restart:
      log-condition-evaluation-delta: false
    livereload:
      enabled: false
  cache:
    type: none

server:
  port: 8888

logging:
  level:
    web: debug
    sql: debug
    springfox:
      documentation: warn
    org:
      apache.shiro: debug
      jooq: info

knife4j:
  enable: true
  setting:
    enableSwaggerModels: false
    enableDocumentManage: false
    enableOpenApi: false

cors:
  allowed-origins: http://localhost:9527, http://localhost.com:9527
