spring:
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
    show-sql: false
    open-in-view: false
  profiles:
    active: dev
  jackson:
    deserialization:
      READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE: true
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true

server:
  servlet:
    context-path: /api/v1
shiro:
  loginUrl: /sys/auth/page/401
  unauthorizedUrl: /sys/auth/page/403

logging:
  level:
    org:
      jooq.Constants: warn

