spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_rest?characterEncoding=UTF-8&serverTimezone=GMT%2b8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&useSSL=false&connectTimeout=30000000
    username: sr
    password: sr123
    sqlScriptEncoding: UTF-8
    initialization-mode: never
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    log-request-details: true
  devtools:
    restart:
      log-condition-evaluation-delta: false
    livereload:
      enabled: false

server:
  port: 8888

logging:
  level:
    org:
      springframework.web: debug
      hibernate.SQL: debug

knife4j:
  enable: true
  setting:
    enableSwaggerModels: false
    enableDocumentManage: false
    enableOpenApi: false
